name: Check Notebook Outputs

on:
  pull_request:
    branches: ['main']
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install nbstripout
      run: pip install nbstripout
    - name: Check notebooks have no outputs
      run: |
        find . -name '*.ipynb' -not -path './.venv/*' -not -path './Drafts/*' \
          | xargs nbstripout --verify
